django/fruit_shop/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),

    path('products/', include('products.urls')),
    path('api/products/', include('products.urls-rest')),

    path('sells/', include('sells.urls')),
    path('api/sells/', include('sells.urls-rest')),
    path('api/carts/', include('sells.urls-carts-rest')),

    path('', include('shop.urls')),

] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django/products/urls.py
from django.urls import path

from products.views import AjaxFruitForm, AjaxFruitList, AjaxFruitDetail, AjaxFruitCategoryForm, AjaxFruitEditForm

urlpatterns = [
    path('ajax_get_fruit_form', AjaxFruitForm.as_view(), name='fruit-rest-form'),
    path('ajax_get_fruit_edit_form', AjaxFruitEditForm.as_view(), name='fruit-rest-form'),
    path('ajax_get_fruit_category_form', AjaxFruitCategoryForm.as_view(), name='fruit-category-rest-form'),
    path('ajax_get_fruit_list', AjaxFruitList.as_view(), name='fruit-rest-list'),
    path('ajax_get_fruit_detail', AjaxFruitDetail.as_view(), name='fruit-rest-detail'),
]

django/shop/urls.py
from django.urls import path
from shop.views import ShopSinglePage

urlpatterns = [
    path('', ShopSinglePage.as_view(), name='home'),
]

django/products/models.py
from django.db import models


class Product(models.Model):
    """
    Product is the abstract class for every product type
    this makes it possible to extend the product range in the future
    """
    name = models.CharField(max_length=100)
    sku = models.PositiveIntegerField()
    stock_quantity = models.PositiveIntegerField()
    weight_kg = models.DecimalField(max_digits=5, decimal_places=2)
    volume_l = models.DecimalField(max_digits=5, decimal_places=2)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        abstract = True

    def __str__(self):
        return str(self.name)


class Fruit(Product):
    """
    Fruit is a product type
    """
    category = models.ForeignKey('FruitCategory', related_name="fruits", on_delete=models.CASCADE)


class FruitCategory(models.Model):
    """
    FruitCategory is the category where each fruit belongs
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)

django/products/forms.py
from django.forms import ModelForm

from products.models import Fruit, FruitCategory


class FruitForm(ModelForm):
    class Meta:
        model = Fruit
        fields = [
            'name',
            'sku',
            'stock_quantity',
            'weight_kg',
            'volume_l',
            'price',
            'category',
        ]


class FruitCategoryForm(ModelForm):
    class Meta:
        model = FruitCategory
        fields = [
            'name',
        ]

django/products/views/views_fruit_categories.py
from django.urls import reverse_lazy
from django.views import generic

from products.models import FruitCategory
from products.views.views_utils import StaffOnly


class FruitCategoryList(generic.ListView):
    model = FruitCategory
    fields = '__all__'


class FruitCategoryCreate(StaffOnly, generic.CreateView):
    model = FruitCategory
    fields = '__all__'
    success_url = reverse_lazy('fruit_category-list')


class FruitCategoryUpdate(StaffOnly, generic.UpdateView):
    model = FruitCategory
    fields = '__all__'
    success_url = reverse_lazy('fruit_category-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(str(context))
        return context


class FruitCategoryDelete(StaffOnly, generic.DeleteView):
    model = FruitCategory
    success_url = reverse_lazy('fruit_category-list')

django/products/views/views_fruits.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from products.forms import FruitForm, FruitCategoryForm


class AjaxGeneral(generic.TemplateView):
    template_name = None

    def get(self, request, *args, **kwargs):
        return render_to_response(self.template_name, context=RequestContext(request))

    def dispatch(self, request, *args, **kwargs):
        #print('dispatch')
        return super(AjaxGeneral, self).dispatch(request, args, kwargs)


class AjaxFruitForm(AjaxGeneral):
    template_name = 'products/ajax_rest_form_fruit.html'

    def get(self, request, *args, **kwargs):
        context = {'form': FruitForm()}
        template = 'products/ajax_rest_form_fruit.html'
        return render(request, template, context)


class AjaxFruitEditForm(AjaxGeneral):

    def get(self, request, *args, **kwargs):
        context = {'form': FruitForm()}
        template = 'products/ajax_rest_form_edit_fruit.html'
        return render(request, template, context)


class AjaxFruitList(AjaxGeneral):

    def get(self, request, *args, **kwargs):
        template = 'products/ajax_rest_list_fruit.html'
        return render(request, template)


class AjaxFruitDetail(AjaxGeneral):

    def get(self, request, *args, **kwargs):
        template = 'products/ajax_rest_detail_fruit.html'
        return render(request, template)


class AjaxFruitCategoryForm(AjaxGeneral):

    def get(self, request, *args, **kwargs):
        context = {'form': FruitCategoryForm()}
        template = 'products/ajax_rest_form_fruit_category.html'
        return render(request, template, context)

django/products/views/views_fruits_rest.py
from django.forms import model_to_dict
from django.http import JsonResponse, HttpResponse
from django.urls import reverse_lazy
from django.views import View, generic

from products.forms import FruitForm
from products.models import Fruit


class ApiFruit(View):

    def get(self, request, *args, **kwargs):
        if len(kwargs) > 0:
            fruit = Fruit.objects.get(pk=kwargs['id'])
            if fruit:
                data = model_to_dict(fruit)
                return JsonResponse(data, safe=False, status=200)
            else:
                return JsonResponse(data={}, safe=False, status=404)
        else:
            fruits = Fruit.objects.all().values('id', 'name', 'price')
            data = list(fruits)
            return JsonResponse(data, safe=False)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = FruitForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse(data={}, safe=False, status=201)
        else:
            return JsonResponse(data={'errors': dict(form.errors.items())}, safe=False, status=400)

    def delete(self, request, *args, **kwargs):
        print('delete')
        if len(kwargs) > 0:
            fruit = Fruit.objects.get(pk=kwargs['id'])
            if fruit:
                fruit.delete()
                return JsonResponse(data={}, safe=False, status=204)
            else:
                return JsonResponse(data={}, safe=False, status=404)
        else:
            return JsonResponse(data={}, safe=False, status=400)

    def put(self, request, *args, **kwargs):
        print('put')
        print(str(kwargs))
        if len(kwargs) > 0:
            fruit = Fruit.objects.get(pk=kwargs['id'])
            print(str(fruit))
            if fruit:
                print(str(request.POST))
                print(str(request.GET))
                form = FruitForm(request.POST, instance=fruit)
                if form.is_valid():
                    form.save()
                    return JsonResponse(data={}, safe=False, status=204)
                return JsonResponse(data={'errors': dict(form.errors.items())}, safe=False, status=400)
            else:
                return JsonResponse(data={}, safe=False, status=404)
        else:
            return JsonResponse(data={}, safe=False, status=400)

    def patch(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

# JsonResponse(serializers.serialize('json', mensajes), safe=False)

django/products/views/views_utils.py
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import FormView


class StaffOnly(FormView):

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden(render(request, "shop/403.html"))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden(reverse("shop/403.html"))
        return super().post(request, *args, **kwargs)

django/products/templates/products/ajax_rest_detail_fruit.html
<div id="fruit" style="display: none;">
    <h2>[[name]]</h2>
    <div class="row">
        <div class="col-4">sku</div>
        <div class="col-4">[[sku]]</div>
    </div>
    <div class="row">
        <div class="col-4">stock_quantity</div>
        <div class="col-4">[[stock_quantity]]</div>
    </div>
    <div class="row">
        <div class="col-4">weight_kg</div>
        <div class="col-4">[[weight_kg]]</div>
    </div>
    <div class="row">
        <div class="col-4">volume_l</div>
        <div class="col-4">[[volume_l]]</div>
    </div>
    <div class="row">
        <div class="col-4">price</div>
        <div class="col-4">[[price]]</div>
    </div>
</div>
{% if user.is_authenticated and not user.is_staff%}
    {% if not user.is_staff%}
        <div class="col-4"><button type="button" class="addToCart" data-id="[[id]]">Add to Cart</button></div>
    {% endif%}
{% else%}
    <div class="col-4"><a href="{% url 'login' %}" > Login to shop</a></div>
{% endif%}

django/products/templates/products/ajax_rest_form_edit_fruit.html
<h2>Add Fruit</h2>
<form id="fruitForm">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
    {% endfor %}

    <div id="fruit" style="display: none;">
    <div class="row">
        <div class="col-4"><label for="id_name">name</label></div>
        <div class="col-4"><input type="text" id="id_name" name="name" value="[[name]]"></div>
    </div>
    <div class="row">
        <div class="col-4"><label for="id_sku">sku</label></div>
         <div class="col-4"><input type="text" id="id_sku" name="sku" value="[[sku]]"></div>
    </div>
    <div class="row">
        <div class="col-4"><label for="id_stock_quantity">stock_quantity</label></div>
         <div class="col-4"><input type="text" id="id_stock_quantity" name="stock_quantity" value="[[stock_quantity]]"></div>
    </div>
    <div class="row">
        <div class="col-4"><label for="id_weight_kg">weight_kg</label></div>
        <div class="col-4"><input type="text" id="id_weight_kg" name="weight_kg" value="[[weight_kg]]"></div>
    </div>
    <div class="row">
        <div class="col-4"><label for="id_volume_l">volume_l</label></div>
         <div class="col-4"><input type="text" id="id_volume_l" name="volume_l" value="[[volume_l]]"></div>
    </div>
    <div class="row">
        <div class="col-4"><label for="id_category">category</label></div>
         <div class="col-4"><input type="text" id="id_category" name="category" value="[[category]]"></div>
    </div>
    <div class="row">
         <div class="col-4"><label for="id_price">price</label></div>
        <div class="col-4"><input type="text" id="id_price" name="price" value="[[price]]"></div>
    </div>
    <button class="putProduct" type="button" data-id="[[id]]">Save fruit</button>
</div>
</form>

django/products/templates/products/ajax_rest_form_fruit.html
<h2>Add Fruit</h2>
<form id="fruitForm">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
    {% endfor %}

    <table border="1">
        {% for field in form.visible_fields %}
            <tr>
                <th>{{ field.label_tag }}</th>
                <td>
                    {{ field.errors }}
                    {{ field.value|default_if_none:"" }}
                    {{ field }}
                    {{ field.help_text }}
                </td>
            </tr>
        {% endfor %}
    </table>

</div>
    {% if object %}
        <button class="putProduct" type="button">Edit fruit</button>
    {% else %}
        <button id="postProduct" type="button">Create fruit</button>
    {% endif %}
</form>

django/products/templates/products/ajax_rest_form_fruit_category.html
<h2>Add Fruit Category</h2>
<form id="fruitCategoryForm">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
    {% endfor %}

    <table border="1">
        {% for field in form.visible_fields %}
            <tr>
                <th>{{ field.label_tag }}</th>
                <td>
                    {{ field.errors }}
                    {{ field }}
                    {{ field.help_text }}
                </td>
            </tr>
        {% endfor %}
    </table>
    {% if object %}
        <button id="putProductCategory" type="button">Edit fruit category</button>
    {% else %}
        <button id="postProductCategory" type="button">Create fruit category</button>
    {% endif %}
</form>

django/products/templates/products/ajax_rest_list_fruit.html
<h2>Fruits</h2>
<div id="fruits" style="display: none;">
    <div class="row">
        <div class="col-4"><a href="#" class="fruitDetail" data-id="[[id]]">[[name]]</a></div>
        <div class="col-4">[[price]]</div>
        {% if user.is_authenticated%}
            {% if user.is_staff%}
                <div class="col-2"><button type="button" class="editFruit" data-id="[[id]]">Edit</button></div>
                <div class="col-2"><button type="button" class="deleteFruit" data-id="[[id]]">Delete</button></div>
            {% else%}
                <div class="col-4"><button type="button" class="addToCart" data-id="[[id]]">Add to Cart</button></div>
            {% endif%}
        {% else%}
            <div class="col-4"><a href="{% url 'login' %}" > Login to shop</a></div>
        {% endif%}

    </div>
</div>

django/products/templates/products/base_products.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
{% endblock %}

{% block appscripts %}

{% endblock %}